/* Generated by tools/build-methodology-level-data.py. Do not edit manually. */
window.SIMULATION_METHODOLOGY_LEVELS = {
  "schemaVersion": "1.0.0",
  "source": {
    "fileName": "구조Simulation_Level.xlsx",
    "sheetName": "Sheet1",
    "sourceRange": "A1:R57",
    "sourceFileSha256": "d16bebd5cc5122c5bb9397ba99ba06cddbcb7e8e0d601decb45c2748e9161c32",
    "normalizedDataSha256": "348f47374a9f5f9c1c0b78a1c5f7a41b012ab032b92c74c2d5986cebd2c3fff3",
    "normalization": "utf8-compact-json-v1"
  },
  "semantics": {
    "notApplicableValue": null,
    "notApplicableLabel": "미적용",
    "fractionalScoreMeaning": "정수 레벨 사이의 중간 성숙도",
    "scoreMin": 1,
    "scoreMax": 5
  },
  "periods": [
    {
      "id": "baseline",
      "period": "2025-12",
      "label": "25.12",
      "roleLabel": "이전 기준"
    },
    {
      "id": "current",
      "period": "2026-02",
      "label": "26.02",
      "roleLabel": "현황"
    },
    {
      "id": "target",
      "period": "2026-12",
      "label": "26.12",
      "roleLabel": "목표"
    }
  ],
  "businessUnits": [
    {
      "id": "sc",
      "label": "SC"
    },
    {
      "id": "large",
      "label": "대형"
    },
    {
      "id": "medium",
      "label": "중형"
    },
    {
      "id": "auto",
      "label": "Auto"
    }
  ],
  "categories": [
    {
      "id": "static-deformation",
      "label": "정적변형",
      "methodologyCount": 28
    },
    {
      "id": "delamination",
      "label": "박리",
      "methodologyCount": 1
    },
    {
      "id": "vibration",
      "label": "진동",
      "methodologyCount": 5
    },
    {
      "id": "fatigue",
      "label": "피로",
      "methodologyCount": 7
    },
    {
      "id": "impact",
      "label": "충격",
      "methodologyCount": 6
    },
    {
      "id": "thermal-flow",
      "label": "열유동",
      "methodologyCount": 8
    }
  ],
  "methodologies": [
    {
      "id": "structural-001",
      "no": 1,
      "sourceRow": 3,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "Tip Pressure",
      "scores": {
        "baseline": {
          "sc": 5,
          "large": 5,
          "medium": 5,
          "auto": 5
        },
        "current": {
          "sc": 5,
          "large": 5,
          "medium": 5,
          "auto": 5
        },
        "target": {
          "sc": 5,
          "large": 5,
          "medium": 5,
          "auto": 5
        }
      }
    },
    {
      "id": "structural-002",
      "no": 2,
      "sourceRow": 4,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "Prush Probe on Bend",
      "scores": {
        "baseline": {
          "sc": 4,
          "large": null,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": 4,
          "large": null,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": 4,
          "large": null,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-003",
      "no": 3,
      "sourceRow": 5,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "Drop Probe on Bend",
      "scores": {
        "baseline": {
          "sc": 3.5,
          "large": null,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": 3.5,
          "large": null,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": 4,
          "large": null,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-004",
      "no": 4,
      "sourceRow": 6,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "Silicon Pad Pusher 공정",
      "scores": {
        "baseline": {
          "sc": 5,
          "large": null,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": 5,
          "large": null,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": 5,
          "large": null,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-005",
      "no": 5,
      "sourceRow": 7,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "Bolt(Screw) 체결에 의한 제품 변형",
      "scores": {
        "baseline": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 3
        },
        "current": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 3
        },
        "target": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 3
        }
      }
    },
    {
      "id": "structural-006",
      "no": 6,
      "sourceRow": 8,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "Direct Bonding",
      "scores": {
        "baseline": {
          "sc": 4,
          "large": null,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": 4,
          "large": null,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": 4,
          "large": null,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-007",
      "no": 7,
      "sourceRow": 9,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "PAD Printing",
      "scores": {
        "baseline": {
          "sc": 2,
          "large": null,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": 2,
          "large": null,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": 2,
          "large": null,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-008",
      "no": 8,
      "sourceRow": 10,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "Diaphragm",
      "scores": {
        "baseline": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 3
        },
        "current": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 3
        },
        "target": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 3
        }
      }
    },
    {
      "id": "structural-009",
      "no": 9,
      "sourceRow": 11,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "중립면",
      "scores": {
        "baseline": {
          "sc": 4.5,
          "large": 3.5,
          "medium": 4.5,
          "auto": 4.5
        },
        "current": {
          "sc": 4.5,
          "large": 3,
          "medium": 4,
          "auto": 4
        },
        "target": {
          "sc": 4.5,
          "large": 4,
          "medium": 4,
          "auto": 4
        }
      }
    },
    {
      "id": "structural-010",
      "no": 10,
      "sourceRow": 12,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "Deflection (처짐)",
      "scores": {
        "baseline": {
          "sc": 5,
          "large": 5,
          "medium": 5,
          "auto": 5
        },
        "current": {
          "sc": 5,
          "large": 5,
          "medium": 5,
          "auto": 5
        },
        "target": {
          "sc": 5,
          "large": 5,
          "medium": 5,
          "auto": 5
        }
      }
    },
    {
      "id": "structural-011",
      "no": 11,
      "sourceRow": 13,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "Cell Gap 변동",
      "scores": {
        "baseline": {
          "sc": null,
          "large": null,
          "medium": 4,
          "auto": 5
        },
        "current": {
          "sc": null,
          "large": null,
          "medium": 4,
          "auto": 5
        },
        "target": {
          "sc": null,
          "large": null,
          "medium": 4,
          "auto": 5
        }
      }
    },
    {
      "id": "structural-012",
      "no": 12,
      "sourceRow": 14,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "Rollable & Slidable",
      "scores": {
        "baseline": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 1
        },
        "current": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 1
        },
        "target": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 2
        }
      }
    },
    {
      "id": "structural-013",
      "no": 13,
      "sourceRow": 15,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "Bending",
      "scores": {
        "baseline": {
          "sc": 4.2,
          "large": 4,
          "medium": 4,
          "auto": 4
        },
        "current": {
          "sc": 4.2,
          "large": 4,
          "medium": 4,
          "auto": 4
        },
        "target": {
          "sc": 4.2,
          "large": 4,
          "medium": 4,
          "auto": 4
        }
      }
    },
    {
      "id": "structural-014",
      "no": 14,
      "sourceRow": 16,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "COF Bending 공정",
      "scores": {
        "baseline": {
          "sc": 4,
          "large": 4,
          "medium": 4,
          "auto": 4
        },
        "current": {
          "sc": 4,
          "large": 4,
          "medium": 4,
          "auto": 4
        },
        "target": {
          "sc": 4,
          "large": 4,
          "medium": 4,
          "auto": 4
        }
      }
    },
    {
      "id": "structural-015",
      "no": 15,
      "sourceRow": 17,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "T-flex Bending 공정",
      "scores": {
        "baseline": {
          "sc": 4,
          "large": null,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": 4,
          "large": null,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": 4,
          "large": null,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-016",
      "no": 16,
      "sourceRow": 18,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "주름 (Waviness)",
      "scores": {
        "baseline": {
          "sc": 1,
          "large": null,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": 1,
          "large": null,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": 1,
          "large": null,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-017",
      "no": 17,
      "sourceRow": 19,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "제품 열 변형",
      "scores": {
        "baseline": {
          "sc": 4.2,
          "large": 4,
          "medium": 3,
          "auto": 4
        },
        "current": {
          "sc": 4.2,
          "large": 4,
          "medium": 3,
          "auto": 4
        },
        "target": {
          "sc": 5,
          "large": 4,
          "medium": 3,
          "auto": 4
        }
      }
    },
    {
      "id": "structural-018",
      "no": 18,
      "sourceRow": 20,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "제품 열/흡습 변형",
      "scores": {
        "baseline": {
          "sc": 2,
          "large": 3,
          "medium": 3,
          "auto": 4
        },
        "current": {
          "sc": 2,
          "large": 3,
          "medium": 3,
          "auto": 4
        },
        "target": {
          "sc": 2,
          "large": 3,
          "medium": 3,
          "auto": 4
        }
      }
    },
    {
      "id": "structural-019",
      "no": 19,
      "sourceRow": 21,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "Bonding 공정",
      "scores": {
        "baseline": {
          "sc": 3,
          "large": 3,
          "medium": 3,
          "auto": 4
        },
        "current": {
          "sc": 3,
          "large": 3,
          "medium": 3,
          "auto": 4
        },
        "target": {
          "sc": 3,
          "large": 3,
          "medium": 3,
          "auto": 4
        }
      }
    },
    {
      "id": "structural-020",
      "no": 20,
      "sourceRow": 22,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "흑얼룩 패턴 열변형 예측",
      "scores": {
        "baseline": {
          "sc": null,
          "large": 5,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": null,
          "large": 5,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": null,
          "large": 5,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-021",
      "no": 21,
      "sourceRow": 23,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "Press 성형 공정",
      "scores": {
        "baseline": {
          "sc": null,
          "large": 3,
          "medium": 3,
          "auto": null
        },
        "current": {
          "sc": null,
          "large": 3,
          "medium": 3,
          "auto": null
        },
        "target": {
          "sc": null,
          "large": 3,
          "medium": 3,
          "auto": null
        }
      }
    },
    {
      "id": "structural-022",
      "no": 22,
      "sourceRow": 24,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "Spring Back (탄성 복원)",
      "scores": {
        "baseline": {
          "sc": null,
          "large": 3,
          "medium": 3,
          "auto": null
        },
        "current": {
          "sc": null,
          "large": 3,
          "medium": 3,
          "auto": null
        },
        "target": {
          "sc": null,
          "large": 3,
          "medium": 3,
          "auto": null
        }
      }
    },
    {
      "id": "structural-023",
      "no": 23,
      "sourceRow": 25,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "외부 힘에 의한 Crack",
      "scores": {
        "baseline": {
          "sc": 2,
          "large": 2,
          "medium": 3,
          "auto": 4
        },
        "current": {
          "sc": 2,
          "large": 2,
          "medium": 3,
          "auto": 4
        },
        "target": {
          "sc": 2,
          "large": 2,
          "medium": 3,
          "auto": 4
        }
      }
    },
    {
      "id": "structural-024",
      "no": 24,
      "sourceRow": 26,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "Snap Fit 체결",
      "scores": {
        "baseline": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 3
        },
        "current": {
          "sc": null,
          "large": 1,
          "medium": 1,
          "auto": 3
        },
        "target": {
          "sc": null,
          "large": 1,
          "medium": 1,
          "auto": 3
        }
      }
    },
    {
      "id": "structural-025",
      "no": 25,
      "sourceRow": 27,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "Curved/가변형 제품 반발력 예측",
      "scores": {
        "baseline": {
          "sc": 1,
          "large": 3,
          "medium": 3,
          "auto": 3
        },
        "current": {
          "sc": 1,
          "large": 2,
          "medium": 3,
          "auto": 3
        },
        "target": {
          "sc": 2,
          "large": 3,
          "medium": 3,
          "auto": 3
        }
      }
    },
    {
      "id": "structural-026",
      "no": 26,
      "sourceRow": 28,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "Stretchable 구조 변형",
      "scores": {
        "baseline": {
          "sc": 1,
          "large": null,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": 1,
          "large": null,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": 2,
          "large": null,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-027",
      "no": 27,
      "sourceRow": 29,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "공압 실린더 Pusher 공정",
      "scores": {
        "baseline": {
          "sc": 3,
          "large": null,
          "medium": null,
          "auto": 3
        },
        "current": {
          "sc": 3,
          "large": null,
          "medium": null,
          "auto": 3
        },
        "target": {
          "sc": 3,
          "large": null,
          "medium": null,
          "auto": 3
        }
      }
    },
    {
      "id": "structural-028",
      "no": 28,
      "sourceRow": 30,
      "majorCategory": "구조역학",
      "categoryId": "static-deformation",
      "categoryLabel": "정적변형",
      "name": "PKG 파괴 Simulation",
      "scores": {
        "baseline": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-029",
      "no": 29,
      "sourceRow": 31,
      "majorCategory": "구조역학",
      "categoryId": "delamination",
      "categoryLabel": "박리",
      "name": "제품 박리/들뜸",
      "scores": {
        "baseline": {
          "sc": 3,
          "large": null,
          "medium": null,
          "auto": 3
        },
        "current": {
          "sc": 3,
          "large": null,
          "medium": null,
          "auto": 3
        },
        "target": {
          "sc": 3,
          "large": null,
          "medium": null,
          "auto": 3
        }
      }
    },
    {
      "id": "structural-030",
      "no": 30,
      "sourceRow": 32,
      "majorCategory": "구조역학",
      "categoryId": "vibration",
      "categoryLabel": "진동",
      "name": "고유 진동수",
      "scores": {
        "baseline": {
          "sc": null,
          "large": 3,
          "medium": 3,
          "auto": 3
        },
        "current": {
          "sc": null,
          "large": 3,
          "medium": 3,
          "auto": 3
        },
        "target": {
          "sc": 2,
          "large": 3,
          "medium": 3,
          "auto": 3
        }
      }
    },
    {
      "id": "structural-031",
      "no": 31,
      "sourceRow": 33,
      "majorCategory": "구조역학",
      "categoryId": "vibration",
      "categoryLabel": "진동",
      "name": "Random (확률) 진동",
      "scores": {
        "baseline": {
          "sc": null,
          "large": null,
          "medium": 3,
          "auto": null
        },
        "current": {
          "sc": null,
          "large": null,
          "medium": 3,
          "auto": null
        },
        "target": {
          "sc": null,
          "large": null,
          "medium": 3,
          "auto": null
        }
      }
    },
    {
      "id": "structural-032",
      "no": 32,
      "sourceRow": 34,
      "majorCategory": "구조역학",
      "categoryId": "vibration",
      "categoryLabel": "진동",
      "name": "복합 진동",
      "scores": {
        "baseline": {
          "sc": null,
          "large": 1,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": null,
          "large": 1,
          "medium": 1,
          "auto": null
        },
        "target": {
          "sc": null,
          "large": 1,
          "medium": 1,
          "auto": null
        }
      }
    },
    {
      "id": "structural-033",
      "no": 33,
      "sourceRow": 35,
      "majorCategory": "구조역학",
      "categoryId": "vibration",
      "categoryLabel": "진동",
      "name": "이송 환경 조건에 따른 이재기 반력",
      "scores": {
        "baseline": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-034",
      "no": 34,
      "sourceRow": 36,
      "majorCategory": "구조역학",
      "categoryId": "vibration",
      "categoryLabel": "진동",
      "name": "고주파 진동",
      "scores": {
        "baseline": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-035",
      "no": 35,
      "sourceRow": 37,
      "majorCategory": "구조역학",
      "categoryId": "fatigue",
      "categoryLabel": "피로",
      "name": "Rolling 반복 하중",
      "scores": {
        "baseline": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 2
        },
        "current": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 2
        },
        "target": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 2
        }
      }
    },
    {
      "id": "structural-036",
      "no": 36,
      "sourceRow": 38,
      "majorCategory": "구조역학",
      "categoryId": "fatigue",
      "categoryLabel": "피로",
      "name": "Bending 반복 하중",
      "scores": {
        "baseline": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": 1,
          "large": null,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-037",
      "no": 37,
      "sourceRow": 39,
      "majorCategory": "구조역학",
      "categoryId": "fatigue",
      "categoryLabel": "피로",
      "name": "Folding 반복 하중",
      "scores": {
        "baseline": {
          "sc": 1,
          "large": null,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": 1,
          "large": null,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": 2,
          "large": null,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-038",
      "no": 38,
      "sourceRow": 40,
      "majorCategory": "구조역학",
      "categoryId": "fatigue",
      "categoryLabel": "피로",
      "name": "Sliding 반복 하중",
      "scores": {
        "baseline": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 2
        },
        "current": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 2
        },
        "target": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 2
        }
      }
    },
    {
      "id": "structural-039",
      "no": 39,
      "sourceRow": 41,
      "majorCategory": "구조역학",
      "categoryId": "fatigue",
      "categoryLabel": "피로",
      "name": "Stretchable 제품 피로",
      "scores": {
        "baseline": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-040",
      "no": 40,
      "sourceRow": 42,
      "majorCategory": "구조역학",
      "categoryId": "fatigue",
      "categoryLabel": "피로",
      "name": "진동 피로",
      "scores": {
        "baseline": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 1
        },
        "current": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 1
        },
        "target": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 1
        }
      }
    },
    {
      "id": "structural-041",
      "no": 41,
      "sourceRow": 43,
      "majorCategory": "구조역학",
      "categoryId": "fatigue",
      "categoryLabel": "피로",
      "name": "열 피로",
      "scores": {
        "baseline": {
          "sc": 1.7,
          "large": null,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": 1.7,
          "large": null,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": 2,
          "large": null,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-042",
      "no": 42,
      "sourceRow": 44,
      "majorCategory": "구조역학",
      "categoryId": "impact",
      "categoryLabel": "충격",
      "name": "Ball Impact",
      "scores": {
        "baseline": {
          "sc": 3,
          "large": 4,
          "medium": 3,
          "auto": 4
        },
        "current": {
          "sc": 3,
          "large": 4,
          "medium": 3,
          "auto": 4
        },
        "target": {
          "sc": 4,
          "large": 4,
          "medium": 3,
          "auto": 4
        }
      }
    },
    {
      "id": "structural-043",
      "no": 43,
      "sourceRow": 45,
      "majorCategory": "구조역학",
      "categoryId": "impact",
      "categoryLabel": "충격",
      "name": "단위 제품 낙하 충격",
      "scores": {
        "baseline": {
          "sc": 3,
          "large": null,
          "medium": 3,
          "auto": null
        },
        "current": {
          "sc": 3,
          "large": null,
          "medium": 3,
          "auto": null
        },
        "target": {
          "sc": 4,
          "large": null,
          "medium": 3,
          "auto": null
        }
      }
    },
    {
      "id": "structural-044",
      "no": 44,
      "sourceRow": 46,
      "majorCategory": "구조역학",
      "categoryId": "impact",
      "categoryLabel": "충격",
      "name": "Head Impact Criterion",
      "scores": {
        "baseline": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 5
        },
        "current": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 5
        },
        "target": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 5
        }
      }
    },
    {
      "id": "structural-045",
      "no": 45,
      "sourceRow": 47,
      "majorCategory": "구조역학",
      "categoryId": "impact",
      "categoryLabel": "충격",
      "name": "패널 열 충격",
      "scores": {
        "baseline": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 2
        },
        "current": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 2
        },
        "target": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 2
        }
      }
    },
    {
      "id": "structural-046",
      "no": 46,
      "sourceRow": 48,
      "majorCategory": "구조역학",
      "categoryId": "impact",
      "categoryLabel": "충격",
      "name": "Glass Crack",
      "scores": {
        "baseline": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 1
        },
        "target": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": 1
        }
      }
    },
    {
      "id": "structural-047",
      "no": 47,
      "sourceRow": 49,
      "majorCategory": "구조역학",
      "categoryId": "impact",
      "categoryLabel": "충격",
      "name": "누적 Damage Set 내충격",
      "scores": {
        "baseline": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-048",
      "no": 48,
      "sourceRow": 50,
      "majorCategory": "구조역학",
      "categoryId": "thermal-flow",
      "categoryLabel": "열유동",
      "name": "ACF(접착제) 유동",
      "scores": {
        "baseline": {
          "sc": 2,
          "large": 2,
          "medium": 2,
          "auto": null
        },
        "current": {
          "sc": 2,
          "large": 2,
          "medium": 2,
          "auto": null
        },
        "target": {
          "sc": 2,
          "large": 3,
          "medium": 3,
          "auto": null
        }
      }
    },
    {
      "id": "structural-049",
      "no": 49,
      "sourceRow": 51,
      "majorCategory": "구조역학",
      "categoryId": "thermal-flow",
      "categoryLabel": "열유동",
      "name": "통합 열전달",
      "scores": {
        "baseline": {
          "sc": 3,
          "large": 5,
          "medium": 5,
          "auto": null
        },
        "current": {
          "sc": 3,
          "large": 5,
          "medium": 5,
          "auto": null
        },
        "target": {
          "sc": 3,
          "large": 5,
          "medium": 5,
          "auto": null
        }
      }
    },
    {
      "id": "structural-050",
      "no": 50,
      "sourceRow": 52,
      "majorCategory": "구조역학",
      "categoryId": "thermal-flow",
      "categoryLabel": "열유동",
      "name": "구동 PTN에 따른 제품 열전달",
      "scores": {
        "baseline": {
          "sc": null,
          "large": 4,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": null,
          "large": 4,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": null,
          "large": 4,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-051",
      "no": 51,
      "sourceRow": 53,
      "majorCategory": "구조역학",
      "categoryId": "thermal-flow",
      "categoryLabel": "열유동",
      "name": "흡습 기인 불량 (E불량) 수명 예측",
      "scores": {
        "baseline": {
          "sc": null,
          "large": 3,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": null,
          "large": 3,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": null,
          "large": 3,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-052",
      "no": 52,
      "sourceRow": 54,
      "majorCategory": "구조역학",
      "categoryId": "thermal-flow",
      "categoryLabel": "열유동",
      "name": "흡습 농도 예측",
      "scores": {
        "baseline": {
          "sc": null,
          "large": 4,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": null,
          "large": 4,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": null,
          "large": 4,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-053",
      "no": 53,
      "sourceRow": 55,
      "majorCategory": "구조역학",
      "categoryId": "thermal-flow",
      "categoryLabel": "열유동",
      "name": "Air Blow (ESD Tape 부착)",
      "scores": {
        "baseline": {
          "sc": null,
          "large": 3,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": null,
          "large": 3,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": 1,
          "large": 3,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-054",
      "no": 54,
      "sourceRow": 56,
      "majorCategory": "구조역학",
      "categoryId": "thermal-flow",
      "categoryLabel": "열유동",
      "name": "패널 흡착 압력",
      "scores": {
        "baseline": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": null,
          "large": null,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": 2,
          "large": null,
          "medium": null,
          "auto": null
        }
      }
    },
    {
      "id": "structural-055",
      "no": 55,
      "sourceRow": 57,
      "majorCategory": "구조역학",
      "categoryId": "thermal-flow",
      "categoryLabel": "열유동",
      "name": "Side Sealing",
      "scores": {
        "baseline": {
          "sc": 3,
          "large": null,
          "medium": null,
          "auto": null
        },
        "current": {
          "sc": 3,
          "large": null,
          "medium": null,
          "auto": null
        },
        "target": {
          "sc": 3,
          "large": null,
          "medium": null,
          "auto": null
        }
      }
    }
  ],
  "integrity": {
    "methodologyCount": 55,
    "observationCount": 660,
    "numericScoreCount": 288,
    "notApplicableCount": 372,
    "categoryCounts": {
      "정적변형": 28,
      "박리": 1,
      "진동": 5,
      "피로": 7,
      "충격": 6,
      "열유동": 8
    }
  }
};
